# This is a basic workflow to help you get started with Actions

name: Integracion y entrega continua

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      NOMBRES: "Jose Emanuel"
      APELLIDOS: "Chuquimbalqui Salvatierra"
      EDAD: "29"
      VERSION_PROYECTO: "3.0"
     # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Step1 Presentacion 
      - name: presntaci√≥n
        run: |
          echo "Nombres: $NOMBRES"
          echo "Apellidos: $APELLIDOS"
          echo "Edad: $EDAD"

      # Step2 datos generales 
      - name: Datos Generales
        run: echo "Carrera Ing Sist"

      # Step3 Variables de entorno secreto
      - name: variables de entorno secretas
        run: |
          echo "user: ${{ secrets.USER }}"
          echo "password: ${{ secrets.PASSWORD }}"

                
      # Step4 Variables abiertas 
      - name: variables abiertas
        run: |
          echo "Imprmiendo la ultima Version de mi proyecto: $VERSION_PROYECTO"